### DT

In [4]:
# Load libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
import os
import cv2
import numpy as np
from sklearn.metrics import classification_report

In [5]:
DATADIR = '/home/lenin/Documents/kaggle/color_classification/ColorClassification'
CATEGORIES = ['orange','Violet','red','Blue','Green','Black','Brown','White']
IMG_SIZE=100

In [6]:
training_data=[]
def create_training_data():
    for category in CATEGORIES:
        path=os.path.join(DATADIR, category)
        class_num=CATEGORIES.index(category)
        for img in os.listdir(path):
            try:
                img_array=cv2.imread(os.path.join(path,img))
                new_array=cv2.resize(img_array,(IMG_SIZE,IMG_SIZE))
                training_data.append([new_array,class_num])
            except Exception as e:
                pass
create_training_data() 
lenofimage = len(training_data)
print(lenofimage)

107

In [7]:
X=[]
y=[]

for categories, label in training_data:
    X.append(categories)
    y.append(label)
X= np.array(X).reshape(lenofimage,-1)

In [8]:
X = X/255.0
y=np.array(y)
print(y.shape)
print(X.shape)

(107,)
(107, 30000)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [10]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [11]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.48148148148148145

In [12]:
print("Accuracy on unknown data is",classification_report(y_test,y_pred))

Accuracy on unknown data is               precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       0.67      0.33      0.44         6
           2       0.00      0.00      0.00         4
           3       0.67      0.67      0.67         3
           4       0.00      0.00      0.00         1
           5       0.33      0.50      0.40         2
           6       0.44      0.67      0.53         6
           7       0.75      0.75      0.75         4

    accuracy                           0.48        27
   macro avg       0.48      0.49      0.47        27
weighted avg       0.49      0.48      0.47        27

In [13]:
result = pd.DataFrame({'original' : y_test,'predicted' : y_pred})
result

    original  predicted
0          6          5
1          6          6
2          7          7
3          2          6
4          2          6
5          1          1
6          3          5
7          1          2
8          6          4
9          1          6
10         1          6
11         3          3
12         1          1
13         4          3
14         2          7
15         6          6
16         7          7
17         6          6
18         3          3
19         5          2
20         5          5
21         7          1
22         2          6
23         7          7
24         1          2
25         6          6
26         0          0

### Optimizing Decision Tree Performance

In [14]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.4074074074074074

In [15]:
result = pd.DataFrame({'original' : y_test,'predicted' : y_pred})
result

    original  predicted
0          6          6
1          6          0
2          7          7
3          2          6
4          2          6
5          1          5
6          3          5
7          1          6
8          6          4
9          1          5
10         1          5
11         3          3
12         1          1
13         4          4
14         2          6
15         6          0
16         7          7
17         6          4
18         3          3
19         5          0
20         5          5
21         7          1
22         2          6
23         7          7
24         1          0
25         6          6
26         0          0